// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_boatswain = "CgkIyqHa6OAFEAIQEQ"; // <GPGSID>
        public const string achievement_warmed_up = "CgkIyqHa6OAFEAIQDQ"; // <GPGSID>
        public const string achievement_zeus = "CgkIyqHa6OAFEAIQCw"; // <GPGSID>
        public const string leaderboard_high_score__bubble_pop = "CgkIyqHa6OAFEAIQAw"; // <GPGSID>
        public const string achievement_bubble_ninja = "CgkIyqHa6OAFEAIQBg"; // <GPGSID>
        public const string achievement_a_bubbly_beginning = "CgkIyqHa6OAFEAIQBA"; // <GPGSID>
        public const string achievement_cabin_boy = "CgkIyqHa6OAFEAIQEA"; // <GPGSID>
        public const string achievement_professional_zapper = "CgkIyqHa6OAFEAIQCg"; // <GPGSID>
        public const string leaderboard_high_score__bug_zap = "CgkIyqHa6OAFEAIQAQ"; // <GPGSID>
        public const string achievement_bubble_apprentice = "CgkIyqHa6OAFEAIQBQ"; // <GPGSID>
        public const string achievement_expert = "CgkIyqHa6OAFEAIQDw"; // <GPGSID>
        public const string achievement_exterminator = "CgkIyqHa6OAFEAIQDA"; // <GPGSID>
        public const string achievement_commander = "CgkIyqHa6OAFEAIQEg"; // <GPGSID>
        public const string achievement_master_of_all_trades = "CgkIyqHa6OAFEAIQDg"; // <GPGSID>
        public const string achievement_newbie = "CgkIyqHa6OAFEAIQBw"; // <GPGSID>
        public const string achievement_bubble_captain = "CgkIyqHa6OAFEAIQCA"; // <GPGSID>
        public const string achievement_commodore = "CgkIyqHa6OAFEAIQEw"; // <GPGSID>
        public const string achievement_harnessing_the_electric = "CgkIyqHa6OAFEAIQCQ"; // <GPGSID>
        public const string leaderboard_high_score__harpoon = "CgkIyqHa6OAFEAIQFA"; // <GPGSID>

}

